version: '3'
services:
  app:
    container_name: csc174_app
    restart: "no"
    working_dir: /var/www/html/
    build:
      context: ./app/
      dockerfile: dockerfile
    volumes:
      - ./app/src/:/var/www/html/
    ports:
      - 80:80
      - 8080:80
    links:
      - database
    
  database:
    container_name: csc174_database
    restart: "no"
    command: --default-authentication-plugin=mysql_native_password # Required for mysql docker-compose environment vars to work properly
                                                                   # @link: https://stackoverflow.com/a/58579325/2104168
    build:
      context: ./database/
      dockerfile: dockerfile
    volumes:
      - ./database/sql/:/usr/src/sql/
      - ./database/dbdata/:/var/lib/mysql/
      - ./database/initdb/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:8080
    