FROM mysql:5.6.41

# Copy in sql scripts
COPY --chown=mysql:mysql sql/ /usr/src/sql/

# Initialize Database with initdb/ scripts
COPY --chown=mysql:mysql initdb/ItemTracker.sql /docker-entrypoint-initdb.d/
