FROM mysql:5.6.41

# Copy in sql scripts
COPY --chown=mysql:mysql sql/ /usr/src/sql/

# Initialize Database with initdb/ scripts
#RUN "mysql -v --user='root' --password='pass' -e 'source /usr/src/sql/Project.sql'"
COPY --chown=mysql:mysql initdb/Project.sql /docker-entrypoint-initdb.d/
